window.defaultNumber = '+1-888-449-9415 to';
window.defaultText = 'Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...!';
window.text = {
    'xhamster.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'perfectgirls.net': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'gotporn.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'anysex.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'sex.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'bravotube.net': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'mylust.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'manporn.xxx': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'anybunny.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'txxx.com': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...',
    'findbestsolution.xyz': 'Your |%model%| Your Apple ID was Recently used at APPLE STORE for $345.69 Via Apple Pay Pre-Authorization. We have placed those request on hold to ensure Your Safety and Security. Not you? Immediately Call Apple Support at +1 (888) 449-7564 to Freeze it!...'
};
